product-name: pivotal-container-service
product-properties:
  .pivotal-container-service.pks_tls:
     value:
       cert_pem: ((pks_tls.certificate))
       private_key_pem: ((pks_tls.private_key))
  .properties.bosh-metric-sink-node-exporter:
    value: false
  .properties.bosh-metric-sink-outputs:
    value: |
      [[outputs.discard]]
  .properties.cloud_provider:
    selected_option: gcp
    value: GCP
  .properties.cloud_provider.gcp.master_service_account:
    value: ((gcp-pks-master-sa)) 
  .properties.cloud_provider.gcp.network:
    value: ((subdomain-name))-pcf-network
  .properties.cloud_provider.gcp.project_id:
    value: ((gcp-project-id))
  .properties.cloud_provider.gcp.worker_service_account:
    value: ((gcp-pks-worker-sa)) 
  .properties.log_sink_resources_deploy:
    value: true
  .properties.metric_sink_resources_deploy:
    value: true
  .properties.network_selector:
    selected_option: flannel
    value: flannel
  .properties.network_selector.flannel.pod_network_cidr:
    value: 10.200.0.0/16
  .properties.network_selector.flannel.service_cluster_cidr:
    value: 10.100.200.0/24
  .properties.node_exporter_deploy:
    value: false
  .properties.oidc_selector:
    selected_option: disabled
    value: disabled
  .properties.pks-vrli:
    selected_option: disabled
    value: disabled
  .properties.pks-vrops:
    selected_option: disabled
    value: disabled
  .properties.pks_api_hostname:
    value: ((pks-api-fqdn))
  .properties.plan1_selector:
    selected_option: active
    value: Plan Active
  .properties.plan1_selector.active.admission_plugins:
    value: []
  .properties.plan1_selector.active.allow_privileged_containers:
    value: true
  .properties.plan1_selector.active.description:
    value: 'Example: This plan will configure a lightweight kubernetes cluster. Not
      recommended for production workloads.'
  .properties.plan1_selector.active.kubelet_drain_delete_local_data:
    value: true
  .properties.plan1_selector.active.kubelet_drain_force:
    value: true
  .properties.plan1_selector.active.kubelet_drain_force_node:
    value: false
  .properties.plan1_selector.active.kubelet_drain_grace_period:
    value: 10
  .properties.plan1_selector.active.kubelet_drain_ignore_daemonsets:
    value: true
  .properties.plan1_selector.active.kubelet_drain_timeout:
    value: 0
  .properties.plan1_selector.active.master_az_placement:
    value:
    - ((az1))
  .properties.plan1_selector.active.master_instances:
    value: 1
  .properties.plan1_selector.active.max_worker_instances:
    value: 50
  .properties.plan1_selector.active.name:
    value: small
  .properties.plan1_selector.active.worker_az_placement:
    value:
    - ((az1))
  .properties.plan1_selector.active.worker_instances:
    value: 1
  .properties.plan2_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan3_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan4_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan5_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan6_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan7_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan8_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan9_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan10_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan11_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan12_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan13_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.proxy_selector:
    selected_option: disabled
    value: Disabled
  .properties.syslog_selector:
    selected_option: disabled
    value: disabled
  .properties.telemetry_installation_purpose_selector:
    selected_option: not_provided
    value: not_provided
  .properties.telemetry_selector:
    selected_option: disabled
    value: disabled
  .properties.uaa:
    selected_option: internal
    value: internal
  .properties.uaa_pks_cli_access_token_lifetime:
    value: 600
  .properties.uaa_pks_cli_refresh_token_lifetime:
    value: 21600
  .properties.uaa_pks_cluster_client_access_token_lifetime:
    value: 600
  .properties.uaa_pks_cluster_client_refresh_token_lifetime:
    value: 21600
  .properties.wavefront:
    selected_option: disabled
    value: disabled
  .properties.worker_max_in_flight:
    value: 1
  .properties.vm_extensions:
    value:
    - public_ip
network-properties:
  network:
    name: pks
  other_availability_zones:
  - name: ((az1))
  service_network:
    name: pks-services
  singleton_availability_zone:
    name: ((az1))
resource-config:
  pivotal-container-service:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
    internet_connected: true
    elb_names:
    - tcp:((pks_lb_backend_name))
errand-config:
  delete-all-clusters:
    pre-delete-state: true
  pks-nsx-t-precheck:
    post-deploy-state: false
  smoke-tests:
    post-deploy-state: false
  upgrade-all-service-instances:
    post-deploy-state: true
  wavefront-alert-creation:
    post-deploy-state: false
  wavefront-alert-deletion:
    pre-delete-state: false

