product-name: harbor-container-registry
product-properties:
  .properties.auth_mode:
    selected_option: db_auth
    value: db_auth
  .properties.clair_updater_interval:
    value: 0
  .properties.customize_container_network:
    selected_option: default
    value: default
  .properties.hostname:
    value: ((product-url))
  .properties.initial_delay_minutes:
    value: 60
  .properties.log_insight:
    selected_option: disabled
    value: disabled
  .properties.no_proxy:
    value: 127.0.0.1,localhost,.local,.internal,log,db,redis,nginx,core,portal,postgresql,jobservice,registry,registryctl,clair
  .properties.registry_storage:
    selected_option: filesystem
    value: filesystem
  .properties.vm_monitor:
    selected_option: no_monitor
    value: no_monitor
  .properties.with_clair:
    value: true
  .properties.with_notary:
    value: true
network-properties:
  network:
    name: infrastructure
  other_availability_zones:
  - name: ((az1))
  singleton_availability_zone:
    name: ((az1))
resource-config:
  harbor-app:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    elb_names: []
    instance_type:
      id: automatic
    instances: automatic
    internet_connected: true
    persistent_disk:
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
  smoke-testing:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    elb_names: []
    instance_type:
      id: automatic
    instances: automatic
    internet_connected: true
    swap_as_percent_of_memory_size: automatic
errand-config:
  smoke-testing:
    post-deploy-state: when-changed
  uaa-deregistration:
    pre-delete-state: false