---

resources:
- name: platform-automation-tasks
  type: s3
  source:
    bucket: pivnet-files
    region_name: region
    access_key_id: MKWP2KC73UCDRWFNQXDF
    secret_access_key: nFJi4Mi4laJJxhocOwKlriitr9kHmOG2skp6UkTO
    endpoint: minio.test-cluster-001.pks.galaxy.env2.k8scloud.cf
    skip_ssl_verification: true
    regexp: platform-automation-tasks-(.*).zip

- name: platform-automation-image
  type: s3
  source:
    bucket: pivnet-files
    region_name: region
    access_key_id: MKWP2KC73UCDRWFNQXDF
    secret_access_key: nFJi4Mi4laJJxhocOwKlriitr9kHmOG2skp6UkTO
    endpoint: minio.test-cluster-001.pks.galaxy.env2.k8scloud.cf
    skip_ssl_verification: true
    regexp: platform-automation-image-(.*).tgz

- name: config
  type: git
  source:
    uri: ((pipeline-repo))
    private_key: ((plat-auto-pipes-deploy-key.private_key))
    branch: pks1.6

credhub-interpolate: &credhub-interpolate
  image: platform-automation-image
  file: platform-automation-tasks/tasks/credhub-interpolate.yml
  params:
    CREDHUB_CLIENT: ((credhub-client))
    CREDHUB_SECRET: ((credhub-secret))
    CREDHUB_SERVER: ((credhub-server)) 
    CREDHUB_CA_CERT: ((credhub-ca-cert))
    PREFIX: ((credhub-prefix))
  input_mapping:
    files: config
  output_mapping:
    interpolated-files: interpolated-config



jobs:
- name: install-ops-manager
  serial: true
  plan:
    - get: platform-automation-image
      params:
        unpack: true
      trigger: true
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: config
    - task: credhub-interpolate
      <<: *credhub-interpolate
    - task: download-product
      image: platform-automation-image
      file: platform-automation-tasks/tasks/download-product-s3.yml
      params:
        CONFIG_FILE: download-ops-manager.yml

      input_mapping:
        config: interpolated-config

    